
#ifndef __TASK_PRIORITIES_H
#define __TASK_PRIORITIES_H

#define MONITOR_TASK_PRIORITY 1
#define MAX_MIN_TASK_PRIORITY 2
#define ALARM_TASK_PRIORITY 3
#define TEMPERATURE_TASK_PRIORITY 3
#define BUBBLE_LEVEL_TASK_PRIORITY 3
#define HIT_BIT_TASK_PRIORITY 3
#define LCD_TASK_PRIORITY 4
#define PWM_TASK_PRIORITY 4

#define ALARM_TASK_QUEUE_SIZE 2
#define MAX_MIN_TASK_QUEUE_SIZE 2
#define LCD_TASK_QUEUE_SIZE 4

#endif
